apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-local-deployment
  namespace: k3s-local
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k3s-local
  template:
    metadata:
      labels:
        name: k3s-local
    spec:
      containers:
        - name: k3s
          image: nginx:1.14.2
          imagePullPolicy: Always
          ports:
            - name: k3s
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
              