apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3s-local-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: ""
spec:
  ingressClassName: k3s-local
  rules:
  - host: k3s.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: k3-local-service
              port:
                number: 80